class PageEvents:
    PAGE_LOADED = 'Page.loadEventFired'
    DOM_CONTENT_LOADED = 'Page.domContentEventFired'
    FILE_CHOOSER_OPENED = 'Page.fileChooserOpened'
    FRAME_ATTACHED = 'Page.frameAttached'
    FRAME_DETACHED = 'Page.frameDetached'
    FRAME_NAVIGATED = 'Page.frameNavigated'
    JS_DIALOG_CLOSED = 'Page.javascriptDialogClosed'
    JS_DIALOG_OPENING = 'Page.javascriptDialogOpening'
    LIFECYCLE_EVENT = 'Page.lifecycleEvent'
    WINDOW_OPENED = 'Page.windowOpen'
    DOCUMENT_OPENED = 'Page.documentOpened'
    FRAME_STARTED_LOADING = 'Page.frameStartedLoading'
    FRAME_STOPPED_LOADING = 'Page.frameStoppedLoading'
    DOWNLOAD_PROGRESS = 'Page.downloadProgress'
    DOWNLOAD_WILL_BEGIN = 'Page.downloadWillBegin'
